<script setup>
import { ref, onMounted, computed } from 'vue'
import { useI18n } from 'vue-i18n';
import { generateInsertTarget, insertHard } from '@/assets/insert'
import { getCode } from '@/assets/utils';
import { saveTwee } from '@/assets/save.js';

const { t, locale } = useI18n();

const customWidgets = ref(JSON.parse(localStorage.getItem('customWidgets')) || {})
const savedNames = computed(() => Object.keys(customWidgets.value))
const widgetName = ref(savedNames.value[0] || 'new')
const tip = ref({ text: '', color: '' })
const isShown = ref(false)
const editingName = ref(''),
      editingTwee = ref(''),
      editingDisplay = ref(null),
      useHTML = ref(false)
let showEditor,
    customInsert, customDelete, customExport,
    editingSave, editingInsert, editingCancel

onMounted(() => {
  const dolEditor = document.querySelector('div.passage');
  showEditor = () => {
    isShown.value = true
    generateInsertTarget(editingDisplay.value)
  }
  const editingHTML = computed(() => {
    return useHTML.value ? editingDisplay.value.textContent : editingDisplay.value.innerHTML;
  })

  customInsert = () => {
    if (widgetName.value === 'new') {
      showEditor();
      return;
    }
    generateInsertTarget(dolEditor);
    insertHard(customWidgets.value[widgetName.value].html || customWidgets.value[widgetName.value], `<<${widgetName.value}>>`);
  }

  customDelete = () => {
    if (widgetName.value === 'new') return;
    delete customWidgets.value[widgetName.value];
    localStorage.setItem('customWidgets', JSON.stringify(customWidgets.value));
  }

  customExport = () => {
    let twee = `<!-- Generated by DOL-pancake -->\n:: Widget ${Date.now()} [widget]\n`;

    Object.entries(customWidgets.value).forEach(([name, widget]) => {
      twee += `\n<<widget "${name}">>\n${
        widget.twee || getCode(widget.html || widget)
      }\n<</widget>>\n`;
    });

    const blob = new Blob([twee], { type: 'text/plain' });
    saveTwee(blob, 'widgets');
  }

  editingSave = () => {
    if (editingName.value === '') return
    if (customWidgets.value[editingName.value]) {
      tip.value = { text: `${t('widget.duplicated')} ${editingName.value}`, color: 'red' }
      return
    }
    customWidgets.value[editingName.value] = {
      html: editingHTML.value || `<span class="noDisplay">${editingName.value}</span>`,
      twee: editingTwee.value,
    };
    localStorage.setItem('customWidgets', JSON.stringify(customWidgets.value));
    tip.value = { text: `${editingName.value} ${t('widget.success')}`, color: 'gold' }
  }

  editingInsert = () => {
    if (editingName.value === '' && editingHTML.value === '') return
    generateInsertTarget(dolEditor);
    insertHard(editingHTML.value || `<span class="noDisplay">${editingName.value || editingTwee.value}</span>`,
               editingTwee.value || getCode(editingHTML.value));
  }

  editingCancel = () => {
    isShown.value = false
    generateInsertTarget(dolEditor)
  }
})
</script>

<template>
<div class="item" id="customWidget">
  {{ $t('insertCustomWidgets') }}：
  <select v-model="widgetName" @change="() => { if (widgetName === 'new') showEditor() }">
    <option v-for="name in savedNames" :key="name">{{ name }}</option>
    <option value="new">{{ $t('new') }}</option>
  </select>
  <button @click="customInsert" class="small">{{ $t('confirm') }}</button>
  <button @click="customDelete" class="small">{{ $t('delete') }}</button>
  <button @click="customExport" class="small">{{ $t('exportAll') }}</button>
</div>

<div v-show="isShown" id="customEditor">
<div class="item">
    <label>{{ $t('widget.name') }}：</label>
    <input v-model="editingName" type="text" :placeholder="$t('widget.tip1')" />
</div>
<div class="item" style="display: flex; flex-wrap: wrap;">
    <label>{{ $t('widget.display') }}：</label>
    <div ref="editingDisplay" id="editingDisplay" :class="locale.replace('-', '')" contenteditable="true"></div>
</div>
<div class="item" style="display: flex; flex-wrap: wrap;">
    <label for="twee">twee：</label>
    <textarea v-model="editingTwee" name="twee" :placeholder="$t('widget.tip2')"></textarea>
</div>
<div class="item">
    <button @click="editingSave" class="small">{{ $t('save') }}</button>
    <button @click="editingInsert" class="small">{{ $t('insert') }}</button>
    <button @click="editingCancel" class="small">{{ $t('cancel') }}</button>
    <label for="useHTML" style="font-size: .9em;">{{ $t('useHTML') }}</label>
    <input v-model="useHTML" type="checkbox" name="useHTML" />
</div>
<div class="item" style="font-size: .9em;"><span :class="tip.color">{{ tip.text }}</span></div>
</div>
</template>

<style>
#customEditor {
	margin-left: 1em;
	input[type="text"] {
		width: auto;
	}
	textarea {
		color: #eee;
		background-color: transparent;
		border: 1px solid #444;
		padding: .34em .4em;
		width: 250px;
		height: 70px;
    font-size: .9rem;
	}
	#editingDisplay {
		color: #eee;
		background-color: transparent;
		border: 1px solid #444;
		padding: .34em .4em;
		width: 300px;
		height: 70px;
		display: inline-block;
		overflow: auto;
		resize: both;
		cursor: text;

		&:empty::before {
			content: 'Use buttons above, or tick "Use HTML" and input HTML';
			font-size: .9rem;
			color: gray;
		}

    &.zh:empty:before {
      content: '请直接使用上方按钮插入内容，或勾选“使用HTML”后输入HTML';
    }

    &.zhTW:empty:before {
      content: '請直接使用上方按鈕插入內容，或勾選「使用HTML」後輸入HTML';
    }

    &.zhHK:empty:before {
      content: '請直接使用上方按鈕插入內容，或勾選「使用HTML」後輸入HTML';
    }
	}
}
</style>