<script setup>
import { computed, ref, watch } from 'vue'
import { saveTwee, saveJSON } from '@/assets/save.js'
import { getCode } from '@/assets/utils.js'
import { useI18n } from 'vue-i18n'
import ToolTip from '../ToolTip.vue'
import { store } from '@/assets/store'

const { t } = useI18n()

const savingName = ref(''),
      savingType = ref('passage')
const savingDup = ref(false)

function savingOperate() {
  const dolEditor = document.querySelector('div.passage');

  savingDup.value = false

  if (savingName.value === '') return
  if (store.savedCode[savingType.value][savingName.value]) {
    return savingDup.value = true
  }

  store.savedCode[savingType.value][savingName.value] = {
    code: getCode(dolEditor.innerHTML, false),
    html: dolEditor.innerHTML,
  }

  localStorage.setItem('savedCode', JSON.stringify(store.savedCode));
}

const savedMethod = ref('load'),
      savedType = ref('passage')
const savedNames = computed(() => {
  return Object.keys(store.savedCode[savedType.value] || {})
}),
      savedName = ref(savedNames.value[0] || '')

watch(savedNames, (names) => {
    savedName.value = names[0] || ''
})

function savedOperate() {
  const dolEditor = document.querySelector('div.passage');

  if (savedMethod.value === 'load') {
    dolEditor.innerHTML = store.savedCode[savedType.value][savedName.value].html;
  } else if (savedMethod.value === 'delete') {
    delete store.savedCode[savedType.value][savedName.value];
    localStorage.setItem('savedCode', JSON.stringify(store.savedCode));
  } else if (savedMethod.value === 'export') {
    let twee = '<!-- Generated by DOL-pancake -->';
    if (savedType.value === 'passage') {
      Object.entries(store.savedCode.passage).forEach(([name, passage]) => {
        twee += `\n:: ${name}\n${passage.code}\n`;
      })
    } else {
      twee += `\n:: Widgets ${Date.now()} [widget]\n`;
      Object.entries(store.savedCode.widget).forEach(([name, widget]) => {
        twee += `\n<<widget "${name}">>\n${widget.code}\n<</widget>>\n`;
      })
    }

    const blob = new Blob([twee], { type: 'text/plain' });
    saveTwee(blob, `${savedType.value}s`);
  }
}

const settingsMethod = ref('export')

function settingsOperate() {
  if (settingsMethod.value === 'export') {
    const json = JSON.stringify(localStorage)
    const blob = new Blob([json], { type: 'application/json' })
    saveJSON(blob, 'dol-pancke-config')
  } else if (settingsMethod.value === 'import') {
    const input = document.createElement('input')
    input.type = 'file'
    input.accept = 'application/json'
    input.addEventListener('change', (event) => {
      const reader = new FileReader()
      reader.readAsText(event.target.files[0])
      reader.onload = () => {
        const json = JSON.parse(reader.result)

        Object.entries(json).forEach(([key, item]) => {
          localStorage.setItem(key, item)
          if (['savedCode', 'customWidgets'].includes(key)) {
            return store[key] = JSON.parse(item)
          }
          store[key] = item
        })

        const dolEditor = document.querySelector('div.passage')
        if (store.temp) dolEditor.innerHTML = store.temp
      }
    })
    input.click()
  } else if (settingsMethod.value === 'reset') {
    localStorage.clear()
    store.theme = ''
    store.savedCode = {
      widget: {},
      passage: {},
    }
    store.temp = ''
    store.customWidgets = {}
    const dolEditor = document.querySelector('div.passage')
    dolEditor.innerHTML = t('placeholder')
  }
}
</script>

<template>
    <div class="item advanced" hidden="1">
      <label>{{ $t('savePassage.1') }}</label>
      <input type="text" v-model="savingName">
      {{ $t('savePassage.2') }}
      <select v-model="savingType"><option>passage</option><option>widget</option></select>
      <button @click="savingOperate" class="small">{{ $t('confirm') }}</button>
      <span class="red" v-show="savingDup" style="font-size: .9em">{{ t('duplicated') }} {{ savingType }} {{ savingName }}</span>
    </div>
    <div class="item advanced" hidden="1">
      <select v-model="savedMethod">
        <option value="load">{{ $t('load') }}</option>
        <option value="delete">{{ $t('delete') }}</option>
        <option value="export">{{ $t('exportAll') }}</option>
      </select>
      <label>{{ $t('saved') }}</label>
      <select v-model="savedType">
        <option>passage</option>
        <option>widget</option>
      </select>
      <select v-model="savedName" v-show="!['export', 'clear'].includes(savedMethod)">
        <option v-for="name in savedNames" :key="name">{{ name }}</option>
      </select>
      <button @click="savedOperate" class="small">{{ $t('confirm') }}</button>
    </div>
    <div class="item advanced" hidden="1">
      <select v-model="settingsMethod">
        <option value="export">{{ $t('export') }}</option>
        <option value="import">{{ $t('import') }}</option>
        <option value="reset">{{ $t('reset') }}</option>
      </select>
      <label>{{ $t('settings') }}</label>
      <button @click="settingsOperate" class="small">{{ $t('confirm') }}</button>
      <ToolTip>{{ $t('settingsTip') }}</ToolTip>
    </div>
</template>
